#define USE_NETCDF4 
#define USE_GRIBAPI 
#define USE_ECCODES 
#undef AFWA_GRIB_CONFIGS 
#undef USE_HDF4 
#undef USE_HDFEOS2 
#define USE_HDF5 
#undef USE_MINPACK 
#undef RTMS 
#undef PETSc 
#undef INC_WATER_PTS
#undef COUPLED
#undef USAF_LIS75_SMDA 
